### ISSUE TITLE
No user feedback on errors

### ISSUE THREAD

**Issue by DrasilZA** [KaddaOK/KaddaOKTools#1]
**Describe the bug**
When the app runs into a problem with recognizing, there are no errors displayed and it seems like the app is busy

**To Reproduce**
Enter a random string as the key on the recognize tab and click on recognize

**Expected behavior**
That an error is displayed to the user and that the recognizing does not appear to be working

**Desktop (please complete the following information):**
 - App Version 0.0.6
 - Windows 11 Pro

**Comment by KaddaOK** [comment]
Sorry for the delay in looking at this!  Winter holiday did not go as expected 😅

Unfortunately, I can't reproduce the issue as described.  
If I enter a random string as the Key, I get an `AuthenticationFailure` properly logged, 
and if I enter a random string as the Location/Region, I get a `ConnectionFailure` properly logged ☹

![image](https://github.com/KaddaOK/KaddaOKTools/assets/151568451/ccc8ea26-b091-495c-b350-a722a3d72d56)

Can you please confirm your repro steps?

**Comment by DrasilZA** [comment]
I've sent you a dm on discord

**Comment by KaddaOK** [comment]
@DrasilZA Source code is now available if you want to try to get to the bottom of the issue you're experiencing (I'm guessing it's network-related but I can't say for sure)

**Comment by DrasilZA** [comment]
I just pulled the repo, and it worked the first time with no issues. I didn't even need to debug. I also downloaded the latest release, and it worked. Then, I downloaded version 0.0.6 and tried again, and it worked as well. I'm guessing there was an issue with dependencies on my side?
