### ISSUE TITLE
Speech recognition language selection

### ISSUE THREAD

**Issue by DrasilZA** [KaddaOK/KaddaOKTools#2]
Add a drop down/textbox for the user to specify the language code from the [supported languages](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=stt#supported-languages) that should be used in the recognition

**Comment by KaddaOK** [comment]
Added in v0.0.7.

![image](https://github.com/KaddaOK/KaddaOKTools/assets/151568451/c0fc5dba-0d1d-4853-8855-401a849a073f)
