### ISSUE TITLE
UI issue on Edit tab

### ISSUE THREAD

**Issue by DrasilZA** [KaddaOK/KaddaOKTools#3]
**Describe the bug**
The UI on EditLinesView get mixed up when an item is removed from CurrentProcess.ChosenLines, but the data in the collection is still correct.

**To Reproduce**
1. Go to Edit tab
2. Click the ⤴ button on a few lines
3. The words in the lines should be mixed up

**Expected behavior**
The UI should display the correct data

**Screenshots**
![output](https://github.com/KaddaOK/KaddaOKTools/assets/100489639/f1d78717-2e19-4b6f-a23f-2d647e2ba873)

**Desktop:**
 - App Version - 0.0.7.0
 - Windows 11 Pro 23H2

**Comment by DrasilZA** [comment]
Just did a test on v0.0.6.0, and did not get the same issue

**Comment by KaddaOK** [comment]
Oof.

All I did was change it from a `<StackLayout>` to a `<WrapLayout>`...

but it appears that there's [a bug in WrapLayout](https://github.com/AvaloniaUI/Avalonia/issues/5869), which has been sitting there with a `help-wanted` tag for a few years.

May have to switch it back to `<StackLayout>` and lose the wrapping of really long lines...  

I'll fix it in the next version one way or another.  Thanks for your patience @DrasilZA!

**Comment by KaddaOK** [comment]
Fixed in 0.0.8: I changed it to an `<ItemsControl>` with a `<WrapPanel>` for a panel template, which apparently does not suffer from the same problem.  🤷‍♂️
